### ISSUE TITLE
Let's make it easy to flip a battery!

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#133]
@ariel-phet @arouinfar @kathy-phet @samreid Can we add a battery flip button? The Java sim had one of these and it was ***mighty*** convenient. No more having to delete a battery and get a new one! No more having to cut two ends and reconnect the opposite way! Now you can just select a battery and press the "flip" button! It would probably be best placed to the left of the voltage slider while editing, similar to this placement: https://github.com/phetsims/circuit-construction-kit-common/issues/73#issuecomment-283505455

Thoughts??

For phetsims/QA/issues/33.

**Comment by kathy-phet** [comment]
I like this suggestion!

**Comment by arouinfar** [comment]
I also like this suggestion @phet-steele. I don't remember having a discussion about flipping the battery (just the bulb terminals), but this seems like a useful feature.

Any thoughts about the mockup in https://github.com/phetsims/circuit-construction-kit-common/issues/73#issuecomment-283505455 @ariel-phet @samreid @kathy-phet?

There's not a font awesome icon for flip/mirror/reflect, but the prevailing design seems to be similar to what I mocked up. For comparison, here are Illustrator's reflect icons: 

![image](https://user-images.githubusercontent.com/8419308/29091454-42c9f602-7c40-11e7-9cd7-c93c1f9ed41b.png)

I think the vertical reflection icon would be the best choice.

**Comment by arouinfar** [comment]
@phet-steele suggested sandwiching an iconic battery between the refresh arrows:
![image](https://user-images.githubusercontent.com/8419308/29092177-a1c765b6-7c42-11e7-82a4-b555b36c7e1f.png)

I think this would clearer than a generic reflect icon.

**Comment by kathy-phet** [comment]
I like Steele's suggestion. It's basically a rotate icon. You can rotate 180 or flip ... so this would be cuing rotate 180 I think.

**Comment by samreid** [comment]
Proposed implementation is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.139/circuit-construction-kit-dc_en.html

The panel now looks like this for batteries:
![image](https://user-images.githubusercontent.com/679486/29099523-260ba5b0-7c63-11e7-9c1a-0a4b45fc7754.png)

Design notes:
1. I originally tried a different icon for low voltage battery and high voltage battery, but it threw off the icon metrics so the icon sizes were different. When I made the battery images the same height, it seemed odd that they were different width.  So I went with the low voltage battery icon.
2. I considered having the icon switch to schematic when the user selects schematic mode, but I realized it would have the same problem with respect to sizing, and since it is intended to be an icon, I think it is OK to remain as a low-voltage battery image (this icon always appears on the screen in the schematic/lifelike radio buttons anyways).
3. The low voltage battery is vertically symmetric and looks great when rotated.  The high voltage battery looks somewhat odd when rotated. I decided to keep it this way because the model implementation was trivial and it's what would happen if you rotated the component by dragging the vertices:
![image](https://user-images.githubusercontent.com/679486/29099507-10ccad02-7c63-11e7-8e10-839f331f34e0.png)
4. It looks like the battery flip button is 1px-2px too tall
5. The slider is centered for batteries but not for resistors.  (The entire panel is centered, and the slider is only in the middle of the panel for batteries).  Should this be changed?

Assigned to @arouinfar @phet-steele and @kathy-phet for review and discussion.

**Comment by arouinfar** [comment]
Looks really good @samreid!! 

In regards to points (1) and (2), I think it's actually preferable to use the same icon for the standard, high-V, and schematic batteries. Originally, I was thinking we could use an all-black iconic battery, perhaps in the style of the font awesome [battery-full icon](http://fontawesome.io/icon/battery-full/). Alternatively, I could modify the icon to be completely filled in.
![image](https://user-images.githubusercontent.com/8419308/29126011-7b743b30-7cda-11e7-8714-de3d06347331.png)

@phet-steele @kathy-phet @samreid any thoughts about the icon itself? I don't find it too odd to use the standard battery in the icon, but I wanted to see if you felt otherwise or may prefer an iconic look.


(3) I am not at all bothered by the upside-down high-V warning label. After all, this is what the battery would look like if the user rotated the battery on their own.

(4) Not sure I follow... the buttons look the same size to me.

(5) I think centering the entire panel looks natural, so no need to change.

**Comment by samreid** [comment]
> I don't find it too odd to use the standard battery in the icon, but I wanted to see if you felt otherwise or may prefer an iconic look.

I think it's best to use the standard battery icon for consistency with the one that appears in the radio buttons (and not introduce a 3rd representation for battery)

> (4) Not sure I follow... the buttons look the same size to me.

It's pretty close!

**Comment by samreid** [comment]
On the other hand, I'm somewhat concerned about the "gold on yellow" contrast problem:

![image](https://user-images.githubusercontent.com/679486/29127022-1ca14d5c-7cdd-11e7-9de5-4d087a4e4c1c.png)

**Comment by arouinfar** [comment]
Here are some rough mockups using the font awesome battery icon 
![image](https://user-images.githubusercontent.com/8419308/29129062-df1ddcce-7ce2-11e7-835f-09fde86452c1.png)

**Comment by samreid** [comment]
Those would probably work.  Another possibility would be to change the button color:

![image](https://user-images.githubusercontent.com/679486/29129320-a31ae856-7ce3-11e7-9349-d48c33dad9ae.png)

Or possibly a lighter yellow?

**Comment by arouinfar** [comment]
@samreid I worked on this a bit with @kathy-phet, and we thought this icon worked nicely
![image](https://user-images.githubusercontent.com/8419308/29140245-19926838-7d07-11e7-8181-aa7739a057f7.png)

If you don't have any objections/suggestions, I'll send you the asset.

**Comment by samreid** [comment]
Let's go for it!

**Comment by arouinfar** [comment]
Great! I'll cleanup the artwork and send you an icon for the battery.

**Comment by arouinfar** [comment]
Sent! Back to you @samreid.

**Comment by samreid** [comment]
The new icon is available here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.150/circuit-construction-kit-dc_en.html

@arouinfar can you please review?

**Comment by arouinfar** [comment]
Love it! Thanks @samreid.
