### ISSUE TITLE
[iPad2] Laggy behavior when dragging components

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#140]
For https://github.com/phetsims/QA/issues/33.

I've noticed a pretty big lag when dragging components around the play area, even in uncomplicated situations. A few examples:

The top layer of the series ammeter becomes disjointed from the body. See [video](https://drive.google.com/a/colorado.edu/file/d/0BwZJWzOg9l4DMEdBYWdlb1ZyNVU/view?usp=sharing). To reproduce:
1. On startup, open Lab
2. Take series ammeter out of toolbox
3. Drag series ammeter around play area

The halo around the bulb, labels, and selection rectangle all have a pretty severe lag when dragged. See [video](https://drive.google.com/a/colorado.edu/file/d/0BwZJWzOg9l4DRG9xb1dnNlowMnc/view?usp=sharing). To reproduce:
1. On startup, build a simple battery + bulb circuit.
2. Max battery voltage (might not be necessary, but helps)
3. Drag bulb around play area, the halo and label will lag behind the bulb.
4. Tap component to edit value, then drag the component around the play area. The rectangle and value will lag behind the component.

Both of the above examples also demonstrate that the component itself lags quite a bit behind the user's finger. The problem is quite a bit worse when dealing with a complicated (but not unrealistic) circuit like this one. Here's a [video](https://drive.google.com/a/colorado.edu/file/d/0BwZJWzOg9l4DVUFBbmlQZXBLRE0/view?usp=sharing) of dragging the wire between the two bulbs around the play area. 
![file_000](https://user-images.githubusercontent.com/8419308/29430479-c78bb264-8351-11e7-8c93-4c184afb6c44.png)

Couldn't find a convenient way to get the text off the iPad, so I suppose a screenshot'll do.
![file_000](https://user-images.githubusercontent.com/8419308/29429596-7e3760b6-834e-11e7-8912-d85c56932b29.png)

**Comment by samreid** [comment]
@jonathanolson and I decided to look into pooling charges in ChargeLayout, that may help the most.

**Comment by samreid** [comment]
The videos reveal an implementation detail that circuit elements, solder, charges, vertices are rendered in WebGL whereas light bulb brightness rays, ammeter readouts, sensors, highlights, values and cut buttons are rendered in SVG. The main reason for this is that our scenery WebGL support can render images and solid, unstroked rectangles but not text or other shapes.

@jonathanolson also pointed out that iOS safari WebGL Rendering is a frame ahead of other SVG and DOM rendering in: https://github.com/phetsims/scenery/issues/611 . That is probably why the WebGL part leads ahead of the SVG parts.

The proposal in https://github.com/phetsims/circuit-construction-kit-dc/issues/140#issuecomment-323449947 will not help the problem in the first video (which shows the series ammeter readout panel lagging behind the series ammeter), since charges are not reallocated when dragging a single fixed-length component.  However, it may help general performance when resizing a wire (even if connected to other parts).

It seems impractical to render dynamic text in WebGL at the moment, so it may make the most sense for the text to remain in SVG.

Some possibilities I considered are:
1. Leave it as-is, which will retain good performance for charge animation and dragging out many components, but leaves this SVG - WebGL syncing problem (which may not be a pedagogical problem--unless it is too distracting)
2. Experiment with using SVG to render the full stack.  Using dev.155 and dragging a single battery on iPad2, I see 27fps (svg) vs 47fps (webgl).  For animating charges around a battery-wire-resistor-wire circuit, I see 59fps (webgl) and 30fps (svg).  For dragging a battery while a battery-wire-resistor-wire circuit animates, I see 20fps (svg) and 42fps (webgl).

Also, it may be possible to move the series ammeter panel (but not the text) to WebGL, so only the text would lag behind when dragging.

Putting the highlight rectangles in WebGL would mean they have to be in front of the sensors and the `seriesAmmeterNodeReadoutPanelLayer`.

Reassigning to @jonathanolson for feedback before discussing further with @arouinfar.  Any other ideas @jonathanolson.

**Comment by samreid** [comment]
Addressing https://github.com/phetsims/circuit-construction-kit-dc/issues/143 may help in some of the circumstances and with general performance when charges are layed out, but as I described in the preceding comment, it won't help with the SVG lagging behind the WebGL.

**Comment by jonathanolson** [comment]
> It seems impractical to render dynamic text in WebGL at the moment

If that's the only constraint (also paths), I'd like to investigate moving some more things to render in WebGL.

Otherwise I'd consider it better to leave as-is now.

@samreid thoughts?

**Comment by samreid** [comment]
@arouinfar adding text and paths to WebGL will be the best way to get excellent performance and lag-free rendering, however, it will take weeks or months to develop it, and we may run into issues regarding internationalization.  My recommendation is to accept the laggy behavior for now and plan for text + paths WebGL for 1.1+

Can you please review everything in this issue and let me know your recommendation?

**Comment by samreid** [comment]
Elevating priority since this is the only issue remaining before next dev test.

**Comment by samreid** [comment]
And adding @ariel-phet to get his feedback as well.

**Comment by arouinfar** [comment]
Thanks for the investigation @jonathanolson @samreid.

Given the time estimate, I'd be okay with leaving things as-is for 1.0. Rendering text in WebGL sounds tricky for i18n, so we may want to discuss if we truly want to go down that route for 1.1+.

 I think it would be good for @ariel-phet to take a look on his iPad2 to confirm that the performance is indeed acceptable for 1.0.

**Comment by samreid** [comment]
@ariel-phet reviewed the behavior with WebGL on iPad2 and determined that it is too laggy and needs to be addressed.  We next checked performance & behavior with webgl=false on iPad2 and determined it looks good: fast enough and no laggy behavior between svg and webgl.  He recommended to put iPad2 as webgl=false for the upcoming dev test.  We could check user agent or perhaps pixel ratio to see if it is iPad2 (perhaps @jonathanolson knows the best way to do so).

WebGL may be important for Android, though may have the same problem with lag between SVG and webgl.  @phet-steele can double test that iPad Air performance is OK using the WebGL.

**Comment by arouinfar** [comment]
Sounds good to me @samreid!

**Comment by samreid** [comment]
@jonathanolson pointed out the lag may be due to iOS Safari 9 more than it relates to the hardware.  So we can use that to identify the svg platforms.

**Comment by samreid** [comment]
Committed changes that check for mobile safari 9 and ready for testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.159/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
We reviewed performance on iPad Air 2 and it is great with webgl=false.  With webgl, there is an inverse lag where the SVG goes in front of the WebGL.  @jonathanolson you might want to know about this, since it is the opposite of what we've seen previously.

**Comment by samreid** [comment]
We also checked an LG Android phone.  The WebGL was 60fps-ish but with a 50ms lag.  Webgl=false had less or no lag but ran at <30fps.

In my opinion our lives will be simpler if we can isolate to use one renderer.

After discussion with @ariel-phet we decided we want to dev test with webgl=false and have QA team keep eyes peeled for performance issues (including but not limited to firefox).

**Comment by samreid** [comment]
SVG version is published here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.160/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
I'll close this issue, and when creating dev/rc test issues I'll ask to check performance.
