### ISSUE TITLE
Edges break circuits

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/circuit-construction-kit-dc#158]
Seen on: Win 10 Chrome

Dragging circuits by the wire (so that it drags the entire circuit) to the edge of the screen on the lab screen tends to compress the circuit if you keep dragging. This is fine, but at a certain point one side of the circuit will 'snap' to the other side of the circuit. If you release at this point, it breaks everything.

Dragging it to the left, up or down freezes it, prevents all interaction with the newly-created Blob, but still works in terms of electrical/voltage calculations.
Step 1: Create a circuit with three batteries on one side, a wire, and then three more batteries. Make sure they're level with each other. Actual composition shouldn't matter.
![image](https://user-images.githubusercontent.com/22551096/30670842-45e4f1f4-9e21-11e7-89b5-612fffc2624c.png)

Step 2: Drag to the left using the wire body, not its vertex. Keep dragging until the right battery composition suddenly snaps to the other side, and then let go. It should do this;
![image](https://user-images.githubusercontent.com/22551096/30670953-cca96c10-9e21-11e7-9795-50bd0c24369e.png)

You can no longer interact with the blob, except adding more components onto it.

If you instead drag it to the right with the same steps as before, instead you get weirdly sized graphics, like fire (which can become huge or tiny)
![image](https://user-images.githubusercontent.com/22551096/30671096-819b0b4c-9e22-11e7-9351-be085d5966c8.png)

Effects are a bit unpredictable; it seems to break a lot of things when it happens. I'll make a gif of the process once i get the recording software working again, since when I broke my computer i broke that too.

For phetsims/QA/issues/51.
Debug Info:
Name: ‪Circuit Construction Kit: DC‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.162/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.162 2017-09-19 15:30:35 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36
Language: en-US
Window: 1366x647
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"3da47e60","branch":"listeners"},"babel":{"sha":"8024993e","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"beecf7e3","branch":"master"},"circuit-construction-kit-common":{"sha":"b0a1151d","branch":"master"},"circuit-construction-kit-dc":{"sha":"0b1708fd","branch":"master"},"dot":{"sha":"d2a1e0db","branch":"master"},"joist":{"sha":"4ac9bf9d","branch":"master"},"kite":{"sha":"5a200449","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"b7e4a6a4","branch":"master"},"scenery-phet":{"sha":"f8b1c996","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"569ad84b","branch":"master"},"tandem":{"sha":"3b161ec8","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by samreid** [comment]
I suspect this was discovered during https://github.com/phetsims/QA/issues/51

@ariel-phet can you please review it and comment on its priority for investigation and fixing before 1.0?

**Comment by BryceAG** [comment]
Here is an example of the huge fire. It is still interactive and once interacted with it will no longer have a huge fire, but also note how the high value resistor graphic gets angled upward so the end top left end no longer lines up with its dashed circle joint (which is connected to the high voltage battery). Interacting with it also moves the resistor graphic into its correct place.

![image](https://user-images.githubusercontent.com/15327201/30715986-8f47db9a-9ed5-11e7-8bbd-ec60f6d308b7.png)

So far the most simple way to reproduce the fire is to make a line in this order: 
[battery 1][wire][battery 2][battery 3][battery 4]
and then dragging by the middle of the wire to the right side. After the graphic "snaps' into a different position, move the mouse left until the right most battery (4) lines up with the left most battery (1) and then releasing. Again the graphics are angled away from the joints.

![image](https://user-images.githubusercontent.com/15327201/30716886-9570b8a4-9ed8-11e7-8fd5-2b79757536e3.png)

The section to the right of the wire has to be 3 objects long for the block to "snap" into a new position during dragging, and having them all be batteries guarantees that the circuit made will cause a fire. Also if the batteries are on the left of the wire and one on the right, and it is dragged off the left edge so that battery 1 and 4 overlap a big fire is made. Other objects could potentially work, but it seems that to create the fire, two batteries must be overlapping each other after you stop dragging and the circuit is made.

**Comment by BryceAG** [comment]
Also, both the odd graphics sizes and the not-interactive blocks are reproducible in the Intro section, and are not limited to the Lab

**Comment by BryceAG** [comment]
Reproduced on Win 7, Mac 10.12, Firefox, Edge, and Safari.

Internet Explorer is an interesting case, because dragging to any edge seems to freeze the entire sim except for the 'reset all,' 'home,' or other lab section (if you froze lab, then Intro, and vice versa) buttons. If the home button or other section is chosen, all functionality works except for trying to return to the screen you froze which will only show the previous screen. But if you click where the home button, other section, or reset all button would be if the frozen section was displaying correctly, then it goes to that screen or resets everything in the frozen section and shows it correctly. This makes me think that the screen is actually interactive, but only the display is messed up and only gets updated if overwritten (home or other section), or reset.

**Comment by BryceAG** [comment]
also dragging to the right edge can make an not interactive blob like with the other edges, but is less common

**Comment by ariel-phet** [comment]
@samreid I am definitely not a fan of bugs that "break" the sim, however, I reproduced this one, and it definitely seems like a pretty specific edge case.

Really nice find @EthanWJohnson but for now, I think we will leave this as a known bug and not worry about it for 1.0 publication (since it seems very unlikely to be encountered during normal use of the sim).

Marking deferred and removing assignees

**Comment by phet-steele** [comment]
Above commit fixes this issue. There may be lingering issues but that's okay 🤞 . As a little bonus, it also helps prevent some multitouch issues.

@ariel-phet this took all but 10 minutes to fix. @samreid thanks for figuring this out with me. @BryceAG @EthanWJohnson good find!
