### ISSUE TITLE
User suggestion: incandescent bulb

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#159]
> Unless I am missing something, it appears that the light bulb
> has a constant resistance and hence is equivalent to a resistor.
> 
> Instead, I suggest that you hard-wire in a typical I vs V curve
> for an incandescent  bulb in order to demonstrate a failure of
> Ohm's law in the form V = I R (for constant R).
> 
> Students could then do an "experiment" to deduce I(V) by
> changing the source voltage and measuring I.
> 
> This should be a small change.  In the longer term it would
> be interesting to couple this to an energy budget for heat
> and light production.

**Comment by arouinfar** [comment]
@oliver-phet this suggestion overlaps a bit with #157 requesting a non-Ohmic bulb, which will be included in a later version (see https://github.com/phetsims/circuit-construction-kit-common/issues/10). 

Despite what the user suggests, this is not a small change. It'll require quite a bit of work, which is why it's being deferred to version 1.1 (or later).

**Comment by oliver-phet** [comment]
Thanks, will let user know this is a planned feature.
