### ISSUE TITLE
Light bulb brightness should be proportionate to power, not current

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#16]
On 2/22/17 4:24 PM, Kathy Perkins wrote:
> Shima, Argenta,
>
> We've found a physics bug in the CCK. It impacts all HTML5 versions. The light bulb ray display is currently displayed as proportional to current only, but it should be proportional to power=IV.
>
> So we will need to issue a new version. We will let you know when that is ready.
>
> Best,
> Kathy 

Here's the code from the Java version which is used to set the intensity:
```js
        double power = Math.abs( getCurrent() * getVoltageDrop() );
        double maxPower = 60;
        if ( power > maxPower ) {
            power = maxPower;
        }
        return Math.pow( power / maxPower, 0.354 );
```

Note the power of 0.354--we may need to fine tune this in the HTML5 version because the bulb intensities don't necessarily match the Java bulb intensities.

I should make this change in the branch then merge to master.

**Comment by samreid** [comment]
I committed a proposed fix above by manually trying to match the Java behavior.  The match is not perfect because the bulb renderers are different.  I also realized there are several issues with the Java implementation, including not showing a broad dynamic range (10 Ohm bulb stops changing brightness past around 25V).  So I'd like to review this with @arouinfar or @ariel-phet or @kathy-phet before publishing something for our collaborators.  I'll publish a dev version.

**Comment by samreid** [comment]
I published a phet-io RC here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.1-phetiorc.1/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

@ariel-phet @arouinfar or @kathy-phet can you please work with me to identify (a) whether the behavior is good enough to publish for Shima and for our Prototype and (b) whether there are changes we should make before publishing the DC version.

**Comment by arouinfar** [comment]
Consider this example:
<img width="948" alt="screen shot 2017-02-23 at 10 12 33 am" src="https://cloud.githubusercontent.com/assets/8419308/23270355/d661f152-f9b0-11e6-9654-069e586a7a4c.png">

Left battery: 9 V
Left current: 6 amps
Left power: 54 W

Right battery: 27 V
Right current: 6 amps
Right power: 162 W (3x larger than left power)

There is hardly a noticeable difference in the size of the halos.  Overlapping the two light bulbs reveals that the one on the left is indeed brighter, but I wouldn't call it 3x brighter.

<img width="506" alt="screen shot 2017-02-23 at 10 12 10 am" src="https://cloud.githubusercontent.com/assets/8419308/23270435/0107fe1a-f9b1-11e6-8272-88b7349c4608.png">

Recreating this example in Java reveals that the this matches the legacy behavior.
![image](https://cloud.githubusercontent.com/assets/8419308/23270697/f4b7c37e-f9b1-11e6-9ad8-88df92bb4d10.png)

Looks like the problem is that the max brightness isn't very large. Compare max brightness (left) and default brightness (right). The resistance was reduced from 4.5 ohms (right) to 1.0 ohms (left). Both batteries are 9 V. This does not seem like enough range to me.
![image](https://cloud.githubusercontent.com/assets/8419308/23271005/1e3f51c0-f9b3-11e6-920e-bdbd686f6088.png)

Here's what the max brightness looked like in the previous version:
![image](https://cloud.githubusercontent.com/assets/8419308/23271145/b5787a26-f9b3-11e6-876f-1a7cd7bf1fd8.png)

I don't think that the max brightness necessarily needs to be this big, but it definitely needs to be larger than it is now. At minimum, I think it should completely fill the dev boundary like so:
![image](https://cloud.githubusercontent.com/assets/8419308/23271319/4ca856dc-f9b4-11e6-935a-3afe9467e951.png)

**Comment by kathy-phet** [comment]
I agree - max brightness should be more like the behavior where it is filling the screen or more than the screen.

**Comment by samreid** [comment]
@arouinfar would you like to recommend a max power?  Or should we try to implement a gradual (instead of sudden) cutoff, like a logistic function, so that we can depict different powers over a wider range?

![image](https://cloud.githubusercontent.com/assets/679486/23290198/400a5486-fa0c-11e6-9fcf-f50512d7368d.png)

**Comment by kathy-phet** [comment]
@samreid, @arouinfar  - I think we could use this sort of shaped curve on the upper end, but the behavior on the bottom end seems good. I think increasing the max brightness will help with the issue significantly -- the max brightness on the Java version seems to be bigger/longer/thicker rays and brighter than on the prototype. It reaches its max at about 60% higher voltage for the test case I did. 

Also, in looking at the original CCK, I really like how the bulb is a clear glass bulb there so it goes completely "dark" (transparent) when the power is 0 and it itself glows with the light going on. It makes it super clear that it is not on at all. I know we worked on getting the wire shape and electron path correct, but can we discuss the transparency issue at some point down the road. No rush on that, but I just wanted to note it since (to me) the original seems clearer pedagogically.

**Comment by samreid** [comment]
Thanks @kathy-phet, I moved the transparency issue to a new issue.

The light bulb library we are using accepts brightness values between 0 and 1.  If I Increase the max by a factor of 20, then a default light bulb maxes out at around 60V and looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/23312858/80aebcea-fa78-11e6-8c96-7c1ad7ee6391.png)

The behavior closer to power=0 is the same as in the previous version.

@kathy-phet @arouinfar thoughts?  Should I try to patch in a decay function?  Or call this good for now?  Should I make other changes before publishing a version for you to test?

**Comment by kathy-phet** [comment]
@samreid , @arouinfar - I think the logistic function would be good to try, but agree it doesn't need to be done for this version. 

This seems a bit too much to me - so I might try something in between. A maxPower of maybe *10 instead of *20? But Amy should chime in too.

**Comment by arouinfar** [comment]
I think increasing the max halo size will be a bit help. I think the logistic function would be a good long-term solution, but not necessary for Stanford.

I agree with @kathy-phet multiplying the max power by 20 makes the halo a bit larger than I'd like. However,  I think 10x would likely be too small. Can you split the difference and multiply it by 15 @samreid?

**Comment by samreid** [comment]
This version uses a factor of 15:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.1-phetiorc.2/wrappers/index/

Anything else to do before sharing to Stanford and creating a new Prototype?

**Comment by arouinfar** [comment]
Using the example from https://github.com/phetsims/circuit-construction-kit-dc/issues/16#issuecomment-282064549, the 162 W bulb is undeniably brighter than the 54 W bulb.
![image](https://cloud.githubusercontent.com/assets/8419308/23316837/42bc0dc8-fa89-11e6-8669-daf7ef91f7b6.png)

I'm pretty happy with the updated brightness. From my perspective, there isn't anything else that would need to be done for Stanford, but I think it would be good if @kathy-phet could take a look too.

**Comment by kathy-phet** [comment]
It looks good to me. 

One last question - we should check with them for the classroom study if they want Show Electrons on by default, or not. It came up in a conversation with Argenta the other day - so best to ask since Sam will be issuing a new version. 
@samreid - Is the default state of Show Electrons something they can set with a query parameter? I know they can hide or show the box, I just don't know if they can set the starting state there?

**Comment by samreid** [comment]
There is no sim-specific custom query parameter for showing/hiding the electrons by default.  There are 16 phet-io variables for it, like  `circuitConstructionKitBlackBoxStudy.exploreScreen.model.circuit.showElectronsProperty` but that would lead to a pretty unwieldy URL.  Should I just add a custom query parameter for that, then whatever they prefer, we can support?  Or should we wait to hear from them?

**Comment by kathy-phet** [comment]
I think a custom parameter would be the best long-term solution for them and their studies. They are going to be using CCK a lot. Thanks!

**Comment by kathy-phet** [comment]
And then that enables them to change the URL!

**Comment by samreid** [comment]
I published a new version here with electrons on by default (to match master development and DC version) and a new query parameter `showElectrons` which can be set to false.

@arouinfar and @kathy-phet one of the early changes in this issue was non-trivial:
https://github.com/phetsims/circuit-construction-kit-common/commit/618d286c99e3458a2e81ed394eb06d3a8fc093da

It has the potential to cause problems when circuits are disposed.  I tested it myself for a few minutes and did not see any issues, but wanted to get a sense of how much you had tested this new RC, or if you want @phet-steele to test it (one platform) for 10 minutes or so.  If you have already tested 1.1.1-rc.1 or higher with respect to disposing circuit elements and resetting, that may be sufficient.

**Comment by kathy-phet** [comment]
Thanks for the heads up, Sam. Lets do some testing. 

Where is the new version published?

**Comment by samreid** [comment]
Oops, I forgot the URL in my preceding comment:

RC.3 is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.1-phetiorc.3/wrappers/index/

**Comment by kathy-phet** [comment]
Can you remind me on this page how to run the sim full screen? without a wrapper? 

Perhaps we should add a "sim only" link to the page -- so that it is easy to check out full screen.

**Comment by samreid** [comment]
4 days ago I added a new link to the top of the wrappers page in https://github.com/phetsims/phet-io/issues/1045 that just shows the simulation, but it will only be available for new publications out of master (or maintenance releases that pick up this change.) . 

The workaround for now is to use the "Events: colorized" link, which launches the simulation full screen without an iframe.

**Comment by arouinfar** [comment]
I've done a little bit of testing on the latest rc with `?showElectrons=false` and everything seems fine. @samreid do you think the changes merit more formalized testing, or is the latest version deliverable as-is?

**Comment by samreid** [comment]
I think a few minutes of testing (that covers disposal of items in the toolbox and resets) is sufficient.

**Comment by samreid** [comment]
@kathy-phet do you want to take a look at RC.3 before I publish it as a new production PhET-iO version, and @arouinfar shares it to our collaborators?

**Comment by kathy-phet** [comment]
@samreid - I tested some, and it looks good to me. I tried some disposals and such. Thanks! 

One small fix (that could be logged for later time) - when a junction is near the bottom, sometimes the "sissors" show up off screen and cannot be accessed.

**Comment by arouinfar** [comment]
@samreid did a little bit more sanity testing, and everything looks good. Can you publish a new production PhET-io version?

**Comment by samreid** [comment]
> One small fix (that could be logged for later time) - when a junction is near the bottom, sometimes the "sissors" show up off screen and cannot be accessed.

@phet-steele made an issue for that in https://github.com/phetsims/circuit-construction-kit-common/issues/257

**Comment by samreid** [comment]
@kathy-phet said:

> Will you be able to post new links for Argenta and Shima today/tonight? There study is March 1.

**Comment by samreid** [comment]
New version is published here: https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.1.1-phetio/wrappers/index/

@arouinfar are you available to send out the new links?

**Comment by samreid** [comment]
I sent out an email, closing.
