### ISSUE TITLE
delete babel/autoport/circuit-construction-kit/ ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-dc#170]
After publishing the first HTML5 version of a sim ported from Java/Flash, the string files in babel/autoport/{{REPO}} are supposed to be manually deleted.  

I realize that there are addition "flavors" of CCK that have not been ported. But it looks like CCK:DC and CCK:DC-VL did not reuse translations from babel/autoport/circuit-construction-kit/.   So I'm guessing that it would be appropriate to delete the autoport files.

**Comment by samreid** [comment]
I can see what @pixelzoom is describing in the sim_port_checklist:

>   - [ ] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked to pull from rosetta to avoid conflicts.

Someone checked off this item in the CCK: DC checklist: https://github.com/phetsims/circuit-construction-kit-dc/issues/48.  Based on the comment revision history, it was either @samreid, @ariel-phet @arouinfar or @phet-steele.  I'm not placing blame but I want to make sure all team members are aware about this step that must be taken in future sim ports.

I removed the autoport in the preceding step, reassigning to @jbphet to pull rosetta to avoid conflicts. Putting at high priority since the checklist said "immediately" and I don't expect pulling rosetta to take too long.

**Comment by jbphet** [comment]
It's actually not necessary to pull the strings for rosetta - it accesses them directly through the GitHub API now.  I've updated the checklist.  Closing.
