### ISSUE TITLE
User suggestion: schematic view for all components and meters

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#18]
> In the classroom we make real circuits, we use phet simulations and we draw circuits on paper. The circuit construction applet looks like the real world. It would be nice if the "symbols" option looks like how we draw on paper. 
![image](https://cloud.githubusercontent.com/assets/5090275/23530537/53f47faa-ff5f-11e6-988a-d33f3c96f199.png)

**Comment by arouinfar** [comment]
@oliver-phet the Java version of CCK has a "Schematic" option to view the circuit elements symbolically (like in the user's screenshot). While CCK: Prototype does not include this feature, CCK: DC will.

**Comment by arouinfar** [comment]
@oliver-phet saw an exchange with one of our users on Twitter about this same issue, and I think he is asking for all components to have a schematic view, including the light bulb and meters. 

![image](https://cloud.githubusercontent.com/assets/8419308/23559741/3f53c952-fff5-11e6-98f5-42e0dde8ddb1.png)

![image](https://cloud.githubusercontent.com/assets/8419308/23559513/7b9b7d02-fff4-11e6-94c4-ec7b11fd5a12.png)

I'm not sure that we will use schematic meters, but we have talked about a more schematic-like bulb in the past. This is something we'll have to discuss further.

**Comment by ariel-phet** [comment]
@arouinfar this suggestion documented here came from the twitter user (I asked him to email phethelp with the suggestion)

**Comment by arouinfar** [comment]
In the 3/9/17 design meeting we briefly discussed the schematic bulb:
* It is tricky to move the vertices when switching between lifelike and schematic, so consider keeping the vertices in the same location for both versions of the bulb.
* What should electron path look like? Should the electrons be visible? The easiest option would be for the electrons to travel along the filament path, even when not visible.
* It's possible to keep the halo glow on the schematic version, though further discussion would be needed.

I've also found two different standard symbols for a lamp:
Indicator lamp ![image](https://cloud.githubusercontent.com/assets/8419308/23815598/ffa7f20e-05a5-11e7-9288-1fe60b5caa2f.png) 

Illuminating lamp ![image](https://cloud.githubusercontent.com/assets/8419308/23815595/f692b870-05a5-11e7-9688-1f5490cdcf1e.png)

The latter option is generally used to represent the bulb as a light source, rather than an indicator (like a warning light on a car's dashboard). I think an illuminating lamp seems like a more natural fit for the bulb in CCK.

I will mock up a few schematic options.

**Comment by arouinfar** [comment]
Goals for schematic view:
* Simplify and standardize the view of the circuit.
* Viewing the electrons does not explicitly support schematic learning goals, so may not be necessary.

Rough draft:
![image](https://cloud.githubusercontent.com/assets/8419308/24017847/4256a14e-0a57-11e7-97c7-ec23faa3ff49.png)

In the toolbox, the schematic view of the bulb would not have the additional wires.
Leave the electrons on for now. We can disable/alter path in the future.

**Comment by arouinfar** [comment]
For 1.0 we will have a more schematic-like bulb, but schematic meters are beyond the scope of the learning goals. I will create a separate issue for the bulb, and then close this one.

**Comment by arouinfar** [comment]
Remaining work for schematic bulb is being tracked in #273. Closing.
