### ISSUE TITLE
User reported issue and suggestion: ammeter, bulb intensity

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#23]
> The simulation is very nice.
>  
> I have some notes  to make:
>  
> 
> 1. The ammeter that measures the current should have two probes and should be connected within the circuit (one should cut the circuit and insert the current probes between the cut edges )
> 
> 2. The shining of the bulb should be increased when current increase and decrease when current decrease.
> 3. Add the name Voltmeter to the voltage measuring instrument and the name Ammeter to the current measuring instrument.
> 4. Please add a switch device that can open and close the circuit . It is very basic demand for  an electronic circuit.

**Comment by arouinfar** [comment]
@oliver-phet here are my thoughts...

> The ammeter that measures the current should have two probes and should be connected within the circuit (one should cut the circuit and insert the current probes between the cut edges )

The user is referring to a multimeter like those typically used in classrooms. The "Ammeter" in the Java CCK behaves like a multimeter when it measures the current. See #24 for more ammeter-specific discussion.

> The shining of the bulb should be increased when current increase and decrease when current decrease.

The brightness of the bulb is proportional to the Power (P = IV). If the voltage is held constant, increasing the current (by decreasing the bulb's resistance, for example) will increase the brightness of the bulb because the power has increased.  Sam addressed this in #16, and I've re-reviewed the behavior of CCK: Prototype -- everything seems fine on my end.

> Add the name Voltmeter to the voltage measuring instrument and the name Ammeter to the current measuring instrument.

We can consider this suggestion, but we generally label meters with the thing they measure (e.g. "Speed") rather than the name of the measuring instrument itself (e.g "Speedometer").

> Please add a switch device that can open and close the circuit . It is very basic demand for an electronic circuit.

CCK: Prototype is not feature complete. CCK: DC will include a switch, but it's still in the design process.
