### ISSUE TITLE
User reported issue: incorrect current reading on amp meter

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#37]
> Test device:​ HP Pavilion G4 1354tx​
> 
> Operating System:​ Windows 10 Edu​
> 
> Browser:​ Chrome​ 57.0.2987.133
> 
> Problem description:​ different current in a parallel​
> 
> Steps to reproduce:​ build a parallel circuit with 10 100 ohm resistor, use a 100v battery. use amp meter to test each point of the circuit then you will find that the c​current is not the same. 
> 
> Severity:​ may mis-lead students​

**Comment by arouinfar** [comment]
@samreid looks like this is related to https://github.com/phetsims/circuit-construction-kit-common/issues/266.

**Comment by samreid** [comment]
@arouinfar: @Denz1994 and I looked at this and saw the following:

![image](https://cloud.githubusercontent.com/assets/679486/25026934/8a481166-2066-11e7-9312-76a72571d150.png)

1 amp downstairs and 10 amps upstairs.  Is this incorrect?

**Comment by arouinfar** [comment]
@samreid @Denz1994 the behavior of the circuit in your screenshot is correct. Perhaps the user built a circuit like this:

<img width="200" alt="screen shot 2017-04-13 at 4 35 05 pm" src="https://cloud.githubusercontent.com/assets/8419308/25027067/5373d1f6-2067-11e7-8209-73e0887f17dd.png"><img width="200" src="https://cloud.githubusercontent.com/assets/8419308/25052728/7794375c-2110-11e7-8cc8-96ea4edaccba.png"><img width="200" src="https://cloud.githubusercontent.com/assets/8419308/25052737/a00ffb94-2110-11e7-92cf-35f68b90a5d0.png">

Building the circuit like this is a bit easier for measurement.
<img src="https://cloud.githubusercontent.com/assets/8419308/25053002/fd484e1e-2111-11e7-9176-57626afb067c.png" width="300"><img src="https://cloud.githubusercontent.com/assets/8419308/25053026/1e0b4c50-2112-11e7-8d9c-3aca065fc0b3.png" width="300">

The top circuit isn't incorrect, though. If the current meter could read on top of the resistors, they would all read 2 amps.

**Comment by samreid** [comment]
@arouinfar is the user seeing the wire resistivity?  What should we do next?

**Comment by arouinfar** [comment]
@samreid I think the user's issue is in how they constructed the circuit. Without adding the extra wires (like the 2nd screenshot in https://github.com/phetsims/circuit-construction-kit-dc/issues/37#issuecomment-294215371), the user isn't able to get a current reading through each resistor because the current meter only reads on top of wires. However, if they turn on electrons, it'd be pretty easy to observe that the electron speed through the resistors is the same, but much slower than the electrons through the battery.

@oliver-phet can you follow up with this user and ask them to send us a screenshot of the circuit they are talking about?

**Comment by oliver-phet** [comment]
Here are two screenshots @arouinfar 
![image 1](https://cloud.githubusercontent.com/assets/5090275/25636134/b77c7952-2f3d-11e7-9928-15a10ec06f40.png)
![image](https://cloud.githubusercontent.com/assets/5090275/25636135/b78d9930-2f3d-11e7-90f0-4a0850b82a45.png)

**Comment by arouinfar** [comment]
Thanks @oliver-phet! 

It looks like the user's issue would be resolved if the current meter read over resistors, as we've discussed in #27. @oliver-phet can you forward the user's email to me?

**Comment by arouinfar** [comment]
Response sent to the user:
>Thank you for reporting this issue. In the screenshots you’ve provided, the current meter is not actually measuring the current in each parallel branch, which is why you’re getting seemingly conflicting readings. With “Show Electrons” turned on, you may be able to observe that the speed of the electrons through each resistor looks the same. However, if you would like to quantitatively measure the current in each branch, you would need to add extra wires to your circuit, like so:
![image](https://cloud.githubusercontent.com/assets/8419308/25963164/998edb04-363d-11e7-8bb0-c1443d09c210.png)
![image](https://cloud.githubusercontent.com/assets/8419308/25963168/9c8e04ba-363d-11e7-848e-aed9c4888bb7.png)
Currently, the current meter is not able to read over resistors, which is why you were unable to measure an equal current in each parallel branch of your circuit. We will be updating the behavior so that the non-contact current meter is able to read over batteries and resistors before we release the simulation to our site.
