### ISSUE TITLE
What should grab bag component resistance values look like?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#64]
They currently look like this:
![image](https://user-images.githubusercontent.com/679486/27796210-724f742e-5fc6-11e7-9cbc-958c91c76732.png)
Discovered during testing in #47

**Comment by samreid** [comment]
Note that these numbers can easily overlap when the items are in a horizontal line.

**Comment by arouinfar** [comment]
@samreid I've also noticed overlapping labels. Honestly, I think scientific notation would be much easier to read (I've had to painstakingly count zeros many times), but I wonder if that would be acceptable for a younger audience. Let's discuss at design.

**Comment by samreid** [comment]
> I think scientific notation would be much easier to read (I've had to painstakingly count zeros many times)

Brainstorming another alternative, we could have it read something like "1 billion Ω" (this is 3 characters shorter than "1000000000.0 Ω"

**Comment by arouinfar** [comment]
@samreid I really like the suggestion to use "1 billion Ω" and (by extension) "1 million Ω". Another alternative would be to display 10^9, rather than full scientific notation (1x10^9).

**Comment by samreid** [comment]
Take away the ".0" and reduce the size.

**Comment by Denz1994** [comment]
Added maxWidths to the circuit elements not typed as 'resistor' or 'highResistanceResistor' and reduced the number of decimal places shown on value readout.

**Comment by samreid** [comment]
The above commit is in a branch named `MASTER` which seems to be different than `master`.  Was this intentional?

Also, the use of the ternary operator seems incorrect.  The code is:

```js
      var decimalPlaces = 1; // amount of decimal places to be rounded
      circuitElement instanceof Resistor && (circuitElement.resistorType !== ('resistor' || 'highResistanceResistor')) ?
      decimalPlaces = 0 : 1;
```

It would be better like this:

```js
      var isGrabBagResistor = circuitElement instanceof Resistor && (circuitElement.resistorType !== ('resistor' || 'highResistanceResistor'));
      var decimalPlaces = isGrabBagResistor ? 0 : 1; // amount of decimal places to be rounded
```

**Comment by Denz1994** [comment]
@samreid I noticed this duplicate branch, as well this morning. Here are the steps I took yesterday:
1. Made some changes in CCK-Common
2. While regression testing, checked out previous SHA for behavior comparison
3. Applied stashed changes.
4. Pushed to repo

I believe between steps 2 &3 I should have checked out master and I might have still been on an old version. So a new 'MASTER' branch was created with my changes instead of them being pushed to 'master'.

Is there a way to merge the two branches and get rid of the 'MASTER' branch? This is assuming my thoughts are correct on this matter.

**Comment by samreid** [comment]
Checkout master, then merge MASTER into master.  Then delete MASTER?

**Comment by Denz1994** [comment]
So, merging the branches doesn't work because Git doesn't recognize capitalization. It keeps saying that everything is up to date, despite being on two different branches. I've run into this problem before when refactoring the capitalization of file names.

I just stashed my changes, deleted my local copy, recloned the repo, and applied my stashed changes. I also deleted the 'MASTER' branch. I believe this fixed and applied the changes needed.

Assigning to @samreid for review and any insight.

**Comment by samreid** [comment]
This code is probably not doing what you expect:

```js
circuitElement.resistorType !== ('resistor' || 'highResistanceResistor')
```

Because `'resistor' || 'highResistanceResistor'` evaluates to `'resistor'`.  The comparisons will have to be separated.

**Comment by samreid** [comment]
I cleaned up the logic a little and reduced the max width a little.  Now it looks like this:

![image](https://user-images.githubusercontent.com/679486/28295383-7c41911c-6b1d-11e7-89cf-6dfcaecbbedb.png)

@Denz1994 can you please double-check the changes?

**Comment by Denz1994** [comment]
Thanks for the changes. They look great.

I am wondering if we should treat high voltage components and resistors the same way? There is a  minor overlap that doesn't affect readability, but we do have an added decimal place that is never changed in the sim. It may give us less clutter to remove it.  I don't know if it is pedagogically useful to have the decimal places on these components. Thoughts @samreid?

![image](https://user-images.githubusercontent.com/13894380/28327500-d9e6ee7e-6ba0-11e7-8f4b-28f89e357625.png)

**Comment by samreid** [comment]
Good point @Denz1994, I'll raise it for discussion in a new issue.  Closing this one.
