### ISSUE TITLE
Prepare a stable version for AAPT

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#76]
@kathy-phet could use a stable version for AAPT next week.

**Comment by samreid** [comment]
I published a dev version here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.80/circuit-construction-kit-dc_en.html

Here is a snapshot of the known open issues on my radar:
![image](https://user-images.githubusercontent.com/679486/28292143-0768c50c-6b0b-11e7-85de-c63147fdbebb.png)

@arouinfar @ariel-phet @kathy-phet can you please do some brief sanity testing so we can determine whether this is stable enough for AAPT?

**Comment by samreid** [comment]
I tested for about 5 minutes on Chrome and noted 3 new issues (none are necessarily deal-breakers).

**Comment by arouinfar** [comment]
@samreid I was using dev.79 earlier today and encountered two deal-breaking issues 
* After awhile the carousel becomes inactive. Components cannot be taken out or returned, and it requires a browser refresh to fix.
* At some point, the cut button stopped working (carousel was still ok). Also required browser refresh to fix.

I don't know if these were known issues that were fixed in dev.80, but I wanted to point them out. I will test dev.80 and see if I can reproduce the above issues.

**Comment by samreid** [comment]
dev.80 is pretty similar to dev.79, I bet the same issues are there.  Please double check and create issues.

**Comment by arouinfar** [comment]
Will do @samreid.

**Comment by arouinfar** [comment]
I've finished testing dev.80 @samreid. I'm still unable to reproduce the freezing carousel. @phet-steele has also tried, but hasn't (yet) reproduced it. It happened in 3 interviews (1 on iPad Air/Safari, 2 on Mac/Chrome). After the students used the sim for awhile, the carousel became unresponsive. Items couldn't be returned or taken out of it, and the browser had to be refreshed to fix the problem.

**Comment by samreid** [comment]
I'm glad to hear interviews were performed on dev.80.  Do you know how long the sim was used before going unresponsive?  Also, did you learn anything else from the interviews that will inform the design or implementation?

**Comment by arouinfar** [comment]
@samreid sorry, I was a bit unclear. The interviews were done on dev.77 (Mac/Chrome), dev.78 (iPad Air/Safari), and dev.79 (Mac/Chrome). I was conducting interviews on Projectile Motion, and there was enough time at the end to let them use CCK:DC, as well.

I'm still reviewing the footage and making some notes, but I won't have any major change requests based on this round of interviews.

**Comment by samreid** [comment]
OK thanks for clarifying!

**Comment by samreid** [comment]
It sounds like the light bulb ghosting was the only blocking issue and there is a proposed fix for that in https://github.com/phetsims/circuit-construction-kit-common/issues/388

Perhaps we should continue testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.83/circuit-construction-kit-dc_en.html

But there have been a number of other commits since then, so this is not really a "stable sha"
![image](https://user-images.githubusercontent.com/679486/28352296-c62d1dc8-6c12-11e7-8ad4-f7d59e9105ea.png)

**Comment by samreid** [comment]
Version dev.85 fixes the carousel lock-up bug:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.85/circuit-construction-kit-dc_en.html . Let's continue testing this one.

**Comment by samreid** [comment]
Tagging for design meeting so we can come up with a plan to make sure something is OK for AAPT.

**Comment by samreid** [comment]
Rotated probes are available in dev.86: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.86/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
Electron opacity is restored, will be ready in next version.

**Comment by samreid** [comment]
I published http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html

This has electron opacity, fixes the 0.0 battery readout, fixes the broken cut button, and fixes the mouse and pointer areas for schematic items.

@arouinfar @ariel-phet @phet-steele can you please test this?  Should I create a QA issue?

**Comment by samreid** [comment]
I went ahead and created a QA issue: https://github.com/phetsims/QA/issues/26

**Comment by arouinfar** [comment]
@phet-steele and I think [dev.91](http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.91/circuit-construction-kit-dc_en.html) will be good to go at AAPT.

@kathy-phet there are a few caveats 
* Conventional current is most stable when using standard batteries/bulbs/resistors. -- @phet-steele is still working on diagnosing the problem, so no issue to reference yet 
* Keep bulbs upright when using conventional current, otherwise the arrow orientation looks odd. See https://github.com/phetsims/circuit-construction-kit-dc/issues/95.
* Don't switch between zoom levels too quickly. Allow for the animation to complete.  See #99.
* The series ammeter generally works pretty well, but sometimes misbehaves if it's not in a complete circuit. See https://github.com/phetsims/circuit-construction-kit-dc/issues/96 and https://github.com/phetsims/circuit-construction-kit-common/issues/391.

**Comment by ariel-phet** [comment]
Considering @samreid emailed @kathy-phet about this version with caveats and she has given her presentation, we can close
